### ISSUE TITLE
What is a one-sentence description of each of these documents on the City's budget page?

### ISSUE THREAD

**Issue by elburnett** [OpenMaine/openbudgets#2]
Budget & Financial Documents
Budget Books
Budget Status Reports
Comprehensive Annual Financial Reports (CAFR)
Jetport Annual Reports
Maine Uniform Accounting and Auditing Practices for Community Agencies
Management Letters
Monthly Statements
Tax Rates
Uniform Guidance Report - Formerly the A-133

**Comment by viktormoon** [comment]
Click [here](https://docs.google.com/document/d/1z2SJyPLMN1PbjcPRNqvEJPI5ITlWNLwwiMNWo0syfq8/edit?usp=sharing) for descriptions of the budget documents on the City of Portland's website.
